# Generated by Django 5.0.1 on 2024-02-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    ('created_at', models.DateTimeField(auto_now_add=True)),
    migrations.CreateModel(
        name='Review',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('text', models.TextField(max_length=300, verbose_name='Впечатления')),
            ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=40, verbose_name='Оценка фильма')),
            ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tv_show.movie')),
        ],
    )